
parser: babel-eslint
plugins:
  - jest
extends:
  - airbnb
  - prettier
  - prettier/react
  - plugin:jest/recommended
env:
  es6: true
  browser: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
rules:
  react/jsx-filename-extension: off
